---
galaxy_info:
  author: Roderik van der Veer
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - kindlyops.superlumic-computername
  - kindlyops.superlumic-cli
  - kindlyops.superlumic-homebrew
  - kindlyops.superlumic-node
  - profile-all
