---

- src: https://github.com/kindlyops/ansible-role-homebrew.git
  name: kindlyops.superlumic-homebrew

- src: https://github.com/kindlyops/ansible-role-osx-defaults.git
  name: kindlyops.superlumic-osx-defaults

- src: https://github.com/kindlyops/ansible-role-computername.git
  name: kindlyops.superlumic-computername

- src: https://github.com/kindlyops/ansible-role-cli.git
  name: kindlyops.superlumic-cli

- src: https://github.com/kindlyops/ansible-role-node.git
  name: kindlyops.superlumic-node
